# SwiftLint Configuration for NekoTan

# Basic rules
disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - trailing_newline
  - file_length
  - type_body_length
  - function_body_length
  - identifier_name
  - cyclomatic_complexity
  - force_unwrapping

opt_in_rules: # some rules are only opt-in
  - anyobject_protocol
  - array_init
  - closure_end_indentation
  - closure_spacing
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - force_cast
  - force_try
  - function_default_parameter_at_end
  - implicitly_unwrapped_optional
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - no_extension_access_modifier
  - no_fallthrough_only
  - no_grouping_extension
  - no_space_in_method_call
  - notification_center_detachment
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - private_action
  - private_outlet
  - private_over_fileprivate
  - private_unit_test
  - protocol_property_accessors_order
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - require_final_where_possible
  - required_enum_case
  - self_in_property_initialization
  - sorted_first_last
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_break_in_switch
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xctfail_message

# Configuration options for rules
line_length:
  warning: 150
  error: 200
  ignores_comments: true
  ignores_urls: true
  ignores_strings: true
  ignores_interpolated_strings: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 300
  error: 500

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded: # excluded identifiers
    - id
    - URL
    - UI
    - API
    - JSON
    - XML
    - CSV
    - SQL
    - PDF
    - HTTP
    - HTTPS
  allowed_symbols: ["_"]

cyclomatic_complexity:
  warning: 10
  error: 15

# Files and directories to include and exclude
included:
  - "App"
  - "Models"
  - "Services"
  - "Sources"
  - "ViewModels"
  - "Views"
  - "Tests"

excluded:
  - "Pods"
  - "Carthage"
  - "Build"
  - "Generated"
  - "NekoTan.xcodeproj"
  - "NekoTan.xcworkspace"
  - "fastlane"
  - "Scripts"

# Reporter for the output
reporter: "xcode"